### ISSUE TITLE
Error caused by changes in upstream: 'handler: argument of type 'coroutine' is not iterable'

### ISSUE THREAD

**Issue by aroop** [kiri-art/docker-diffusers-api-runpod#1]
I am on a Mac and do not have access to a machine with GPU, so I created the docker build in the lambda labs instance and deployed the image to the `runpod`.

When running the endpoint I was getting an error saying that there I was missing a response argument in handler.py file while executing `output = user_src.inference(input)`, so I suppressed the error by passing None as the response parameter.

With the above change, now I encountered an error while running the code due to recent changes in the upstream. The error message I received is as follows:

```
handler: argument of type 'coroutine' is not iterable \ntraceback: Traceback (most recent call last):\n  File \"/opt/conda/envs/xformers/lib/python3.9/site-packages/runpod/serverless/modules/job.py\", line 91, in run_job\n    elif \"error\" in job_output:\nTypeError: argument of type 'coroutine' is not iterable
```

I am new to python and I am lost on how to properly fix the error. Any help would be appreciated.

**Comment by gadicc** [comment]
Hey @aroop 

Thanks for reporting this.  You're right, I totally wasn't thinking about this on the recent upstream changes.  I believe this is working now, and have confirmed this on RunPod.  Some further testing would be great though so I'll be grateful if you could confirm and I'll re-open the issue until then.

The longer explanation (which you don't need to understand) is that a lot of upstream work has been involved with making as much as possible asynchronous, so that we can for e.g. send back status reports while tasks are busy running.  Since RunPod is expecting a synchronous (non-async) function, we had to make a few [modifications](https://github.com/kiri-art/docker-diffusers-api-runpod/commit/61832b26d62c7069f5eee38a4f5ed8ff94af83f4) to accommodate this.

Anyways, let me know how you go and thanks again for reporting.  This is my first Python project too so don't be shy with questions :)

**Comment by aroop** [comment]
Thank you for your prompt response and for addressing the issue. I appreciate your efforts in fixing the error related to the recent upstream changes.

I have tested the functionality on RunPod, and I can confirm that it is now working as expected. The modifications made to accommodate the asynchronous nature of the tasks have resolved the problem.

Once again, thank you for your swift response and for your assistance.
